<?php use Marketplace\Bus\Repository\IncidentRepository as Incidents; ?>
<p class="form-note">Completa todos los campos. Caso relacionado y archivo de evidencia son opcionales. El código BUG se genera al guardar.</p>
<form method="post" enctype="multipart/form-data" class="case-form"><?php csrf_field(); ?>
<section class="panel form-section"><div class="form-section-title"><span>01</span><div><h2>Identificación y seguimiento</h2></div></div>
<div class="field"><label>ID del Incidente</label><p class="case-code"><?= $incident ? e(Incidents::code((int) $incident['id'])) : 'Se genera automáticamente al guardar' ?></p></div>
<div class="field-grid"><?php foreach (['titulo','modulo','severidad','prioridad','estado','asignado_a'] as $field): ?><div class="field"><label for="<?= e($field) ?>"><?= e(Incidents::FIELDS[$field]) ?> *</label><?php if (Incidents::choices($field)): ?><select id="<?= e($field) ?>" name="<?= e($field) ?>" required><option value="">Seleccionar</option><?php foreach (Incidents::choices($field) as $choice): ?><option value="<?= e($choice) ?>" <?= $values[$field] === $choice ? 'selected' : '' ?>><?= e($choice) ?></option><?php endforeach; ?></select><?php else: ?><input id="<?= e($field) ?>" name="<?= e($field) ?>" maxlength="<?= Incidents::limit($field) ?>" required value="<?= e($values[$field]) ?>"><?php endif; ?></div><?php endforeach; ?></div>
<div class="field"><label for="caso_id">Caso relacionado (opcional)</label><select id="caso_id" name="caso_id"><option value="">Sin caso asociado</option><?php foreach ($cases as $item): ?><option value="<?= (int) $item['id'] ?>" <?= (int) ($values['caso_id'] ?? 0) === (int) $item['id'] ? 'selected' : '' ?>><?= e(code_case((int) $item['id']) . ' · ' . $item['modulo']) ?></option><?php endforeach; ?><?php if ($incident && $incident['caso_id'] !== null && !$repository->canAccessCase((int) $incident['caso_id'], $current)): ?><option value="<?= (int) $incident['caso_id'] ?>" <?= (int) ($values['caso_id'] ?? 0) === (int) $incident['caso_id'] ? 'selected' : '' ?>><?= e(code_case((int) $incident['caso_id'])) ?> · Asociación del Administrador</option><?php endif; ?></select><small>Solo puedes seleccionar casos disponibles para tu cuenta. Eliminar un caso conserva el incidente.</small></div></section>
<section class="panel form-section"><div class="form-section-title"><span>02</span><div><h2>Descripción y reproducción</h2></div></div><?php foreach (['descripcion','pasos_reproducir','resultado_esperado','resultado_obtenido'] as $field): ?><div class="field"><label for="<?= e($field) ?>"><?= e(Incidents::FIELDS[$field]) ?> *</label><textarea id="<?= e($field) ?>" name="<?= e($field) ?>" rows="4" maxlength="5000" required><?= e($values[$field]) ?></textarea></div><?php endforeach; ?></section>
<section class="panel form-section"><div class="form-section-title"><span>03</span><div><h2>Evidencia</h2><p>Una captura, un documento o un log del defecto.</p></div></div><div class="field"><label for="evidencia">Archivo de evidencia (opcional)</label><input id="evidencia" name="evidencia" type="file" accept=".png,.jpg,.jpeg,.pdf,.txt,.log" aria-describedby="incident-evidence-help"><small id="incident-evidence-help">PNG, JPG/JPEG, PDF, TXT o LOG, hasta 2 MB. TXT/LOG deben ser texto UTF-8. Si hay errores, selecciona el archivo de nuevo.</small><?php if ($incident && $incident['evidencia_archivo']): ?><p>Archivo actual: <a href="<?= e(url($basePath . '/evidencia?id=' . $incident['id'])) ?>"><?= e($incident['evidencia_nombre']) ?></a></p><label class="checkbox-label"><input type="checkbox" name="quitar_evidencia" value="1" <?= post_text('quitar_evidencia') === '1' ? 'checked' : '' ?>> Quitar evidencia actual (un archivo nuevo la reemplazará)</label><?php endif; ?></div></section>
<div class="form-actions"><a class="button-secondary" href="<?= e(url($returnPath)) ?>">Cancelar</a><button class="button" type="submit"><?= $incident ? 'Guardar cambios' : 'Registrar incidente' ?></button></div></form>
