<?php $fromSearch = !$case && ($_GET['origen'] ?? '') === 'buscador'; $returnPath = $case ? '/casos/ver?id=' . $case['id'] : ($fromSearch ? '/?' . $values['datos_entrada'] : '/casos'); ?>
<a class="back-link" href="<?= e(url($returnPath)) ?>"><?= $case ? '← Volver al caso' : ($fromSearch ? '← Volver al buscador' : '← Volver a los casos') ?></a>
<div class="page-heading"><div><span class="eyebrow">FORMULARIO 01</span><h1><?= $case ? 'Editar caso de prueba' : 'Nuevo caso de prueba' ?></h1><p class="muted">Documenta qué pruebas realizas, cómo las ejecutas y qué resultado obtienes.</p></div><span class="badge badge-pending"><?= $case ? e(code_case((int) $case['id'])) : 'ID automático' ?></span></div>
<?php errors_block($errors); ?>
<?php if (!$case && ($_GET['origen'] ?? '') === 'buscador'): ?><div class="alert alert-success" role="status">Incluimos el módulo, los filtros y el resultado observado en el buscador. Completa el objetivo, la técnica y el procedimiento antes de guardar.</div><?php endif; ?>
<p class="form-note">Los campos marcados con <span aria-hidden="true">*</span> son obligatorios. Observaciones y Evidencia son opcionales.</p>
<form method="post" enctype="multipart/form-data" class="case-form">
<?php csrf_field(); ?>
<section class="panel form-section"><div class="form-section-title"><span>01</span><div><h2>Identificación y técnica</h2><p>Define la funcionalidad y el enfoque de la prueba.</p></div></div>
<div class="field-grid">
<div class="field"><label for="codigo">ID del Caso</label><input id="codigo" value="<?= $case ? e(code_case((int) $case['id'])) : 'Se asigna al guardar (CP-001, CP-002…)' ?>" readonly><small>Se genera a partir del identificador único del registro.</small></div>
<div class="field"><label for="modulo">Módulo / Funcionalidad <span aria-hidden="true">*</span></label><input id="modulo" name="modulo" maxlength="150" required value="<?= e($values['modulo']) ?>" placeholder="Ej.: Inicio de sesión"></div>
<div class="field"><label for="tecnica">Técnica utilizada <span aria-hidden="true">*</span></label><select id="tecnica" name="tecnica" required aria-describedby="technique-help"><option value="">Selecciona una técnica</option><?php foreach (TECNICAS as $technique => $items): ?><option <?= $values['tecnica'] === $technique ? 'selected' : '' ?> value="<?= e($technique) ?>"><?= e($technique) ?></option><?php endforeach; ?></select></div>
<div class="field"><label for="subtecnica">Subtécnica <span aria-hidden="true">*</span></label><select id="subtecnica" name="subtecnica" required><option value="">Selecciona una subtécnica</option><?php foreach (TECNICAS[$values['tecnica']] ?? [] as $item): ?><option <?= $values['subtecnica'] === $item ? 'selected' : '' ?> value="<?= e($item) ?>"><?= e($item) ?></option><?php endforeach; ?></select></div>
</div><p class="technique-help" id="technique-help" aria-live="polite">Caja Negra evalúa entradas y salidas sin examinar el código. Caja Blanca evalúa la estructura interna del código.</p>
<noscript><p class="alert alert-error">Activa JavaScript para actualizar las subtécnicas al seleccionar una técnica.</p></noscript>
</section>
<section class="panel form-section"><div class="form-section-title"><span>02</span><div><h2>Preparación y ejecución</h2><p>Deja un procedimiento que otra persona pueda repetir.</p></div></div>
<?php $prompts = ['objetivo' => '¿Qué comportamiento quieres verificar?', 'precondiciones' => 'Condiciones necesarias antes de ejecutar la prueba.', 'datos_entrada' => 'Valores y datos que utilizarás.', 'pasos_ejecucion' => "1. Abre la funcionalidad.\n2. Introduce los datos.\n3. Ejecuta la acción."]; ?>
<?php foreach ($prompts as $field => $prompt): ?><div class="field"><label for="<?= e($field) ?>"><?= e($labels[$field]) ?> <span aria-hidden="true">*</span></label><textarea id="<?= e($field) ?>" name="<?= e($field) ?>" rows="<?= $field === 'pasos_ejecucion' ? 5 : 3 ?>" maxlength="5000" required placeholder="<?= e($prompt) ?>"><?= e($values[$field]) ?></textarea></div><?php endforeach; ?>
</section>
<section class="panel form-section"><div class="form-section-title"><span>03</span><div><h2>Resultados y evidencia</h2><p>Compara lo esperado con lo que ocurrió.</p></div></div>
<div class="field-grid"><?php foreach (['resultado_esperado', 'resultado_obtenido'] as $field): ?><div class="field"><label for="<?= e($field) ?>"><?= e($labels[$field]) ?> <span aria-hidden="true">*</span></label><textarea id="<?= e($field) ?>" name="<?= e($field) ?>" rows="4" maxlength="5000" required><?= e($values[$field]) ?></textarea></div><?php endforeach; ?></div>
<div class="field field-narrow"><label for="estado">Estado <span aria-hidden="true">*</span></label><select id="estado" name="estado" required><option value="">Selecciona el resultado</option><?php foreach (['Éxito', 'Fallo'] as $status): ?><option <?= $values['estado'] === $status ? 'selected' : '' ?> value="<?= e($status) ?>"><?= e($status) ?></option><?php endforeach; ?></select></div>
<div class="field"><label for="observaciones">Observaciones <span class="optional">Opcional</span></label><textarea id="observaciones" name="observaciones" rows="3" maxlength="5000" placeholder="Anota información adicional para revisar la prueba."><?= e($values['observaciones']) ?></textarea></div>
<div class="field"><label for="evidencia">Evidencia <span class="optional">Opcional</span></label><input id="evidencia" name="evidencia" type="file" accept="image/png,image/jpeg,application/pdf" aria-describedby="evidence-help"><small id="evidence-help">Captura PNG, JPG o PDF, hasta 2 MB. Si hay errores, selecciona el archivo de nuevo.</small>
<?php if ($case && $case['evidencia_archivo']): ?><p>Archivo actual: <a href="<?= e(url('/casos/evidencia?id=' . $case['id'])) ?>"><?= e($case['evidencia_nombre']) ?></a></p><label class="checkbox-label"><input type="checkbox" name="quitar_evidencia" value="1" <?= post_text('quitar_evidencia') === '1' ? 'checked' : '' ?>> Quitar evidencia actual (un archivo nuevo la reemplazará)</label><?php endif; ?></div>
</section>
<div class="form-actions"><a class="button-secondary" href="<?= e(url($returnPath)) ?>">Cancelar</a><button class="button" type="submit"><?= $case ? 'Guardar cambios' : 'Registrar caso' ?> <span aria-hidden="true">→</span></button></div>
</form>
<script type="application/json" id="technique-catalog"><?= json_encode(TECNICAS, JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?></script>
